let a = 10;
document.write("The Value of a is: ", a, "<br>");
document.write("The Value of ++a is: ", ++a, "<br>");
document.write("Now the Value of a is: ", a, "<br>");
document.write("The Value of a++ is: ", a++, "<br>");
document.write("Now the Value of a is: ", a, "<br>");
document.write("The Value of --a is: ", --a, "<br>");
document.write("Now the Value of a is: ", a, "<br>");
document.write("The Value of a-- is: ", a--, "<br>");
document.write("Now the Value of a is: ", a, "<br>");
document.write("..........................................<br>");
let b = 2 , c = 1;
document.write("a is" , b , "<br>");
document.write("b is" , c , "<br>");
let res = --b - --c + ++c + c--;
document.write("Result is" , res , "<br>"); 
document.write("...................<br>");
let name = prompt("Please enter your name");
swal("Hello! ", name);
let num = prompt("Please Enter a Number", "5");
document.write(num," x ", " 1 = ", num*1, "<br>");
document.write(num," x ", " 2 = ", num*2, "<br>");
document.write(num," x ", " 3 = ", num*3, "<br>");
document.write(num," x ", " 4 = ", num*4, "<br>");
document.write(num," x ", " 5 = ", num*5, "<br>");
document.write(num," x ", " 6 = ", num*6, "<br>");
document.write(num," x ", " 7 = ", num*7, "<br>");
document.write(num," x ", " 8 = ", num*8, "<br>");
document.write(num," x ", " 9 = ", num*9, "<br>");
document.write(num," x ", " 10 = ", num*10, "<br>");
document.write("...................<br>");
let sub1 = prompt("Enter Your Subjects");
let mrk1 = +prompt("Enter Your Marks");
let sub2 = prompt("Enter Your Subjects");
let mrk2 = +prompt("Enter Your Marks");
let sub3 = prompt("Enter Your Subjects");
let mrk3 = +prompt("Enter Your Marks");
let totmrk = 100;
document.write("Subject     ","Total Marks     ","Obtain Marks     ","Percentage <br>");
document.write(sub1,"     ",totmrk,"     ",mrk1,"     ",mrk1/totmrk*100,"% <br>");
document.write(sub2,"     ",totmrk,"     ",mrk2,"     ",mrk2/totmrk*100,"% <br>");
document.write(sub3,"     ",totmrk,"     ",mrk3,"     ",mrk3/totmrk*100,"% <br>");
let obtmrk = mrk1 + mrk2 + mrk3;
document.write("     ","300","     ",obtmrk,"     ",obtmrk/300*100,"% <br>");
document.write("..........................................<br>");
