alert("Hello,World!")
alert("Error!Please Enter a Valid Password.")
alert("Welcome to JS Land....\n Happy Coding!")
alert("Welcome to JS Land")
alert("Happy Coding!")
console.log("Hello...I can run JS through my web browser console")
